version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: "admin_avito"
      POSTGRES_HOST: "localhost"
    ports:
      - "5432:5432"



  app:
    environment:
      PORT: "5000"
      DB_PASSWORD: "1"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_NAME: "admin_avito"

    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres